import { describe } from "node:test";
import { normalizeArrayableParams } from "../../src/Typesense/Utils";
import chai from "chai";

let expect = chai.expect;
describe("Utils", function () {
  describe("normalizeArrayableParams", function () {
    it("converts only arrayable params to strings", function () {
      const params = {
        q: "search query",
        query_by: ["title", "description", "tags"],
        query_by_weights: [2, 1, 1],
        prefix: [true, false, true],
        filter_by: "category:=electronics",
        enable_synonyms: true,
        enable_analytics: true,
        filter_curated_hits: false,
        enable_lazy_filter: false,
        sort_by: ["_text_match:desc", "popularity:desc"],
        facet_by: ["category", "brand", "price_range"],
        max_facet_values: 10,
        facet_sample_threshold: 100,
        facet_sample_percent: 20,
        facet_query: "category:electronics",
        facet_query_num_typos: 1,
        facet_return_parent: "product",
        page: 1,
        per_page: 20,
        group_by: ["category", "brand"],
        group_limit: 3,
        group_missing_values: true,
        include_fields: ["title", "description", "price"],
        exclude_fields: ["internal_id", "metadata"],
        highlight_fields: ["title", "description"],
        highlight_full_fields: ["title", "description", "content"],
        highlight_affix_num_tokens: 4,
        highlight_start_tag: "<mark>",
        highlight_end_tag: "</mark>",
        enable_highlight_v1: false,
        snippet_threshold: 30,
        num_typos: [2, 1, 0],
        min_len_1typo: 4,
        min_len_2typo: 8,
        split_join_tokens: "off",
        exhaustive_search: false,
        drop_tokens_threshold: 10,
        drop_tokens_mode: "right_to_left",
        typo_tokens_threshold: 100,
        pinned_hits: ["doc1", "doc2", "doc3"],
        hidden_hits: ["doc4", "doc5"],
        limit_hits: 1000,
        pre_segmented_query: false,
        enable_overrides: true,
        override_tags: ["promotion", "featured"],
        prioritize_exact_match: true,
        prioritize_token_position: true,
        prioritize_num_matching_fields: true,
        search_cutoff_ms: 1000,
        use_cache: true,
        max_candidates: 20,
        infix: ["off", "always", "fallback"],
        preset: "default",
        text_match_type: "max_score",
        vector_query: "embedding_field:([], k:10)",
        "x-typesense-api-key": "xyz123",
        "x-typesense-user-id": "user123",
        offset: 0,
        limit: 100,
        stopwords: "a,an,the",
        conversation: true,
        conversation_model_id: "gpt-4",
        conversation_id: "conv123",
        voice_query: "what is the weather like",
      };

      expect(normalizeArrayableParams(params)).to.deep.equal({
        q: "search query",
        query_by: "title,description,tags",
        query_by_weights: "2,1,1",
        prefix: "true,false,true",
        filter_by: "category:=electronics",
        enable_synonyms: true,
        enable_analytics: true,
        filter_curated_hits: false,
        enable_lazy_filter: false,
        sort_by: "_text_match:desc,popularity:desc",
        facet_by: "category,brand,price_range",
        max_facet_values: 10,
        facet_sample_threshold: 100,
        facet_sample_percent: 20,
        facet_query: "category:electronics",
        facet_query_num_typos: 1,
        facet_return_parent: "product",
        page: 1,
        per_page: 20,
        group_by: "category,brand",
        group_limit: 3,
        group_missing_values: true,
        include_fields: "title,description,price",
        exclude_fields: "internal_id,metadata",
        highlight_fields: "title,description",
        highlight_full_fields: "title,description,content",
        highlight_affix_num_tokens: 4,
        highlight_start_tag: "<mark>",
        highlight_end_tag: "</mark>",
        enable_highlight_v1: false,
        snippet_threshold: 30,
        num_typos: "2,1,0",
        min_len_1typo: 4,
        min_len_2typo: 8,
        split_join_tokens: "off",
        exhaustive_search: false,
        drop_tokens_threshold: 10,
        drop_tokens_mode: "right_to_left",
        typo_tokens_threshold: 100,
        pinned_hits: "doc1,doc2,doc3",
        hidden_hits: "doc4,doc5",
        limit_hits: 1000,
        pre_segmented_query: false,
        enable_overrides: true,
        override_tags: "promotion,featured",
        prioritize_exact_match: true,
        prioritize_token_position: true,
        prioritize_num_matching_fields: true,
        search_cutoff_ms: 1000,
        use_cache: true,
        max_candidates: 20,
        infix: "off,always,fallback",
        preset: "default",
        text_match_type: "max_score",
        vector_query: "embedding_field:([], k:10)",
        "x-typesense-api-key": "xyz123",
        "x-typesense-user-id": "user123",
        offset: 0,
        limit: 100,
        stopwords: "a,an,the",
        conversation: true,
        conversation_model_id: "gpt-4",
        conversation_id: "conv123",
        voice_query: "what is the weather like",
      });
    });
    it("doesn't convert already stringified arrayable params", function () {
      const params = {
        q: "search query",
        // Comma-separated
        query_by: "title,description,tags",
        query_by_weights: [2, 1, 1],
        prefix: [true, false, true],
        filter_by: "category:=electronics",
        enable_synonyms: true,
        enable_analytics: true,
        filter_curated_hits: false,
        enable_lazy_filter: false,
        // Comma-separated
        sort_by: "_text_match:desc,popularity:desc",
        // Comma-separated
        facet_by: "category,brand,price_range",
        max_facet_values: 10,
        facet_sample_threshold: 100,
        facet_sample_percent: 20,
        facet_query: "category:electronics",
        facet_query_num_typos: 1,
        facet_return_parent: "product",
        page: 1,
        per_page: 20,
        group_by: ["category", "brand"],
        group_limit: 3,
        group_missing_values: true,
        // Comma-separated
        include_fields: "title,description,price",
        exclude_fields: ["internal_id", "metadata"],
        // Comma-separated
        highlight_fields: "title,description",
        highlight_full_fields: ["title", "description", "content"],
        highlight_affix_num_tokens: 4,
        highlight_start_tag: "<mark>",
        highlight_end_tag: "</mark>",
        enable_highlight_v1: false,
        snippet_threshold: 30,
        num_typos: [2, 1, 0],
        min_len_1typo: 4,
        min_len_2typo: 8,
        split_join_tokens: "off",
        exhaustive_search: false,
        drop_tokens_threshold: 10,
        drop_tokens_mode: "right_to_left",
        typo_tokens_threshold: 100,
        // Comma-separated
        pinned_hits: "doc1,doc2,doc3",
        // Comma-separated
        hidden_hits: "doc4,doc5",
        limit_hits: 1000,
        pre_segmented_query: false,
        enable_overrides: true,
        // Comma-separated
        override_tags: "promotion,featured",
        prioritize_exact_match: true,
        prioritize_token_position: true,
        prioritize_num_matching_fields: true,
        search_cutoff_ms: 1000,
        use_cache: true,
        max_candidates: 20,
        infix: ["off", "always"],
        preset: "default",
        text_match_type: "max_score",
        vector_query: "embedding_field:([], k:10)",
        "x-typesense-api-key": "xyz123",
        "x-typesense-user-id": "user123",
        offset: 0,
        limit: 100,
        stopwords: "a,an,the",
        conversation: true,
        conversation_model_id: "gpt-4",
        conversation_id: "conv123",
        voice_query: "what is the weather like",
      };

      expect(normalizeArrayableParams(params)).to.deep.equal({
        q: "search query",
        query_by: "title,description,tags",
        query_by_weights: "2,1,1",
        prefix: "true,false,true",
        filter_by: "category:=electronics",
        enable_synonyms: true,
        enable_analytics: true,
        filter_curated_hits: false,
        enable_lazy_filter: false,
        sort_by: "_text_match:desc,popularity:desc",
        facet_by: "category,brand,price_range",
        max_facet_values: 10,
        facet_sample_threshold: 100,
        facet_sample_percent: 20,
        facet_query: "category:electronics",
        facet_query_num_typos: 1,
        facet_return_parent: "product",
        page: 1,
        per_page: 20,
        group_by: "category,brand",
        group_limit: 3,
        group_missing_values: true,
        include_fields: "title,description,price",
        exclude_fields: "internal_id,metadata",
        highlight_fields: "title,description",
        highlight_full_fields: "title,description,content",
        highlight_affix_num_tokens: 4,
        highlight_start_tag: "<mark>",
        highlight_end_tag: "</mark>",
        enable_highlight_v1: false,
        snippet_threshold: 30,
        num_typos: "2,1,0",
        min_len_1typo: 4,
        min_len_2typo: 8,
        split_join_tokens: "off",
        exhaustive_search: false,
        drop_tokens_threshold: 10,
        drop_tokens_mode: "right_to_left",
        typo_tokens_threshold: 100,
        pinned_hits: "doc1,doc2,doc3",
        hidden_hits: "doc4,doc5",
        limit_hits: 1000,
        pre_segmented_query: false,
        enable_overrides: true,
        override_tags: "promotion,featured",
        prioritize_exact_match: true,
        prioritize_token_position: true,
        prioritize_num_matching_fields: true,
        search_cutoff_ms: 1000,
        use_cache: true,
        max_candidates: 20,
        infix: "off,always",
        preset: "default",
        text_match_type: "max_score",
        vector_query: "embedding_field:([], k:10)",
        "x-typesense-api-key": "xyz123",
        "x-typesense-user-id": "user123",
        offset: 0,
        limit: 100,
        stopwords: "a,an,the",
        conversation: true,
        conversation_model_id: "gpt-4",
        conversation_id: "conv123",
        voice_query: "what is the weather like",
      });
    });
  });
});
